extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-maven
  container: maven
pipelines:
  pullRequest:
    build:
      steps:
      - sh: mvn -f \$(find / -type d ! -name docker ! -name .)/ versions:set -DnewVersion=$PREVIEW_VERSION
        name: set-version
      - sh: mvn -f \$(find / -type d ! -name docker ! -name .)/  install
        name: mvn install dependecies
      - sh: mvn -f \$(find / -type d -name docker ! -name .)/  install
  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      - sh: mvn -f \$(find / -type d -name docker ! -name .)/  versions:set -DnewVersion=\$(cat VERSION)
        name: set-version
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: mvn -f \$(find / -type d -name docker ! -name .)/  clean install
        name: mvn-install
