extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-maven-bwce
  container: maven
pipelines:
  pullRequest:
    build:
      steps:
      - sh: mvn -f \$(pwd *.parrent)/ versions:set -DnewVersion=$PREVIEW_VERSION
        name: set-version
      - sh: mvn -f \$(pwd *.parrent)/ package
        name: mvn-package
  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      - sh: mvn -f \$(pwd *.parrent)/ versions:set -DnewVersion=\$(cat VERSION)
        name: set-version
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: mvn -f \$(pwd *.parrent)/ clean package
        name: mvn-package
