extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-maven-bwce
  container: maven
pipelines:
  pullRequest:
    build:
      steps:
      - sh: mvn versions:set -DnewVersion=$PREVIEW_VERSION
        name: set-version
      - sh: cd $(find . -maxdepth 1 -type d -name '*.parent' -printf '%f\n');mvn package
        name: mvn-package
  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      - sh: mvn versions:set -DnewVersion=\$(cat VERSION)
        name: set-version
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: cd $(find . -maxdepth 1 -type d -name '*.parent' -printf '%f\n');mvn clean package
        name: mvn-package
